### PR TITLE
Updating links to RTD

### PR DESCRIPTION
**Pull request by shamsheersc19**
## Purpose
- Updating the links so that our collaborators go to the new sites.
- Also removed links to OpenAeroStruct and OpenConcept because merging this with MACH-Aero-tutorial is planned for the future.

## Type of change
- Documentation update

## Testing
 - Built locally.

### CODE REVIEW

**Comment by anilyil** [comment]
@shamsheersc19 can you also create the `.gitignore` file and add  the `_build` folder to it?

**Comment by shamsheersc19** [comment]
> I believe the same issue is there for the links in the MACH-Aero page: https://github.com/mdolab/docs/blob/master/machFramework/MACH-Aero.rst Can you also fix these?

Thanks. Done.

**Comment by shamsheersc19** [comment]
> @shamsheersc19 can you also create the `.gitignore` file and add the `_build` folder to it?

Done.

**Comment by anilyil** [comment]
@shamsheersc19 I added the reference to the adflow paper and ds_store stuff to gitignore. I am fine with rest of your modifications. let me know if you dont like what I added

**Comment by shamsheersc19** [comment]
Looks good! Please merge. Thanks.

**Pull request merged**
